name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: depot-ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker image
      uses: depot/build-push-action@v1
      with:
        push: false  # Set to true if you want to push to a registry
        tags: user/app:latest
